version: "3"

services:
  backend:
    container_name: gp-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 5676:5676
    volumes:
      - /app/backend/node_module

  frontend:
    container_name: bp-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - /app/frontend/node_module
